### ISSUE TITLE
Not working with Magento ver. 1.9.3.2

### ISSUE THREAD

**Issue by artiumedia** [gsafcik/OrdersPlus#1]
Great to find out about your extension, however I tested it with Magento ver. 1.9.3.2 but Order Grid is still as normal one though I still can see Extension's settings from System-> Configuration ->Orders Plus . but nothing happened to Orders Grid when I edited those settings.

**Comment by gsafcik** [comment]
Hmm, strange. The last version I tested this on was CE 1.9.3.1. I wouldn't have expected an issue like this for a minor release. Are you using flat tables by chance (I haven't tested with flat tables)?

**Comment by gsafcik** [comment]
@artiumedia I just installed CE 1.9.3.2 and can confirm that it **works as expected**. Please give me more details. Are using another extension that overrides the sales order grid page as well? Perhaps a screenshot?

**Comment by gsafcik** [comment]
Closing due to lack of comments.
