### ISSUE TITLE
Long SKU problem

### ISSUE THREAD

**Issue by istoutjesdijk** [gsafcik/OrdersPlus#3]
When a product has a long SKU, the stock in an order will always be displayed as 0

**Comment by gsafcik** [comment]
This issue is fixed in https://github.com/gsafcik/OrdersPlus/pull/7. Please check it out and let me know if it works for you before I merge it into the main code base.

**Comment by istoutjesdijk** [comment]
It seems to work, great fix :+1:

**Comment by gsafcik** [comment]
#7 is merged
